### ISSUE TITLE
Pie_hart

### ISSUE THREAD

**Issue by dedu6ka** [colinb647/pie_chart_addon#5]
Suggestion:
Using the "True retention" addon (or any other method - like redoing existing Learning cards chart), provide the Retention info for the first 3 Learning steps. If the retention is bad or excessive ( >98% ), the user can adjust the step values -- in the timely manner. 

I use some tricks to get the retention for the second step only.  Tricks like:  
* removing the Fuzz
* excluding FAILED Overdue cards  
* excluding all but card-1 
* separating Learning and Relearning cards.

This addon would greatly improve the learning efficiency and pull many users from the low-interval hell and also deepen the memory traces --  by reviewing 'just-in-time' -- ( Anki boasts  this but  takes very-very long time to get to this point; 
Anki Retention chart for the Learning cards muddled with too much 'noise'.  

Please ask for more details if u are interested - i hope.  
Thank you.

**Comment by colinb647** [comment]
Just to clarify, are these stats of interest that you'd like to see in the general Statistics Overview window, or are these specifically within / next to the pie graph?

**Comment by dedu6ka** [comment]
> Just to clarify, are these stats of interest that you'd like to see in the general Statistics Overview window ... ?  

In the General Stats window.

**Comment by colinb647** [comment]
Those are features I can certainly imagine a number of Anki users would be interested to see; however, I feel they're outside the relatively narrow focus of this add-on affecting the pie graph alone.

If you haven't seen them already, I'd suggest taking a look at the [experimentalCardEaseFactor](https://github.com/eshapard/experimentalCardEaseFactor) and/or [Another Retreat](https://ankiweb.net/shared/info/1481634779) addons, which sound generally similar to some of the things you mentioned.

experimentalCardEaseFactor is one of my personal favs, it really seems to cut down the hassle of reaching 'ease equilibrium' compared to the stock version.
